version: '3'

services:
  db:
    build: ./src/database
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
  web:
    build: .
    command: npm start
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/app
    depends_on:
      - db
