version: '3'

services:
  app:
    build: ./app
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
      - /app/node_modules
    links:
      - api
    depends_on:
      - api
    networks:
      - webappnetwork

  api:
    build: ./api
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - db
    networks:
      - webappnetwork
  db:
    build: ./api/database
    restart: always
    container_name: tis4-db
    volumes:
      - ./api/database:/data/db
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge
