-- MySQL Script generated by MySQL Workbench
-- Sun Sep 15 23:36:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema contabilidadedb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `contabilidadedb` ;

-- -----------------------------------------------------
-- Schema contabilidadedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `contabilidadedb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `contabilidadedb` ;

-- -----------------------------------------------------
-- Table `sys_aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_aluno` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sys_aluno` (
  `idsys_aluno` INT NOT NULL AUTO_INCREMENT,
  `periodo` TINYINT(20) NOT NULL,
  `sys_user_idsys_user` INT NOT NULL,
  `sys_turma_idsys_turma` INT NOT NULL,
  PRIMARY KEY (`idsys_aluno`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sys_criador_desafio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_criador_desafio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sys_criador_desafio` (
  `sys_desafio_idsys_desafio` INT NOT NULL,
  `sys_professor_idsys_professor` INT NOT NULL,
  PRIMARY KEY (`sys_desafio_idsys_desafio`, `sys_professor_idsys_professor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sys_criador_trilha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_criador_trilha` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sys_criador_trilha` (
  `sys_trilha_idsys_trilha` INT NOT NULL,
  `sys_professor_idsys_professor` INT NOT NULL,
  PRIMARY KEY (`sys_trilha_idsys_trilha`, `sys_professor_idsys_professor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sys_desafio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_desafio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sys_desafio` (
  `idsys_desafio` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(30) NOT NULL,
  `DataCriacao` DATE NOT NULL,
  `Descricao` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idsys_desafio`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sys_professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_professor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sys_professor` (
  `idsys_professor` INT NOT NULL,
  `Diciplina` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(30) NOT NULL,
  `sys_user_idsys_user` INT NOT NULL,
  PRIMARY KEY (`idsys_professor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sys_pronuciamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_pronuciamento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sys_pronuciamento` (
  `idsys_pronuciamento` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `DataCriacao` DATE NOT NULL,
  `descricao` MEDIUMTEXT NOT NULL,
  `Titulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsys_pronuciamento`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sys_pronuciamento_has_sys_criador_trilha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_pronuciamento_has_sys_criador_trilha` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sys_pronuciamento_has_sys_criador_trilha` (
  `sys_pronuciamento_idsys_pronuciamento` INT NOT NULL,
  `sys_criador_trilha_sys_trilha_idsys_trilha` INT NOT NULL,
  `sys_criador_trilha_sys_professor_idsys_professor` INT NOT NULL,
  PRIMARY KEY (`sys_pronuciamento_idsys_pronuciamento`, `sys_criador_trilha_sys_trilha_idsys_trilha`, `sys_criador_trilha_sys_professor_idsys_professor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sys_pronuciamento_has_sys_desafio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_pronuciamento_has_sys_desafio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sys_pronuciamento_has_sys_desafio` (
  `sys_pronuciamento_idsys_pronuciamento` INT NOT NULL,
  `sys_desafio_idsys_desafio` INT NOT NULL,
  PRIMARY KEY (`sys_pronuciamento_idsys_pronuciamento`, `sys_desafio_idsys_desafio`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sys_questoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_questoes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sys_questoes` (
  `idsys_questoes` INT NOT NULL AUTO_INCREMENT,
  `tipo` CHAR(8) NOT NULL,
  `descricao` MEDIUMTEXT NOT NULL,
  `sys_desafio_idsys_desafio` INT NOT NULL,
  PRIMARY KEY (`idsys_questoes`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sys_trilha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_trilha` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sys_trilha` (
  `idsys_trilha` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `descricao` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idsys_trilha`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sys_turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_turma` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sys_turma` (
  `idsys_turma` INT NOT NULL AUTO_INCREMENT,
  `responsavel` VARCHAR(45) NOT NULL,
  `codigo_da_turma` INT NOT NULL,
  `descricao` MEDIUMTEXT NOT NULL,
  `sys_professor_idsys_professor` INT NOT NULL,
  `sys_trilha_idsys_trilha` INT NOT NULL,
  PRIMARY KEY (`idsys_turma`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `sys_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `sys_user` (
  `idsys_user` INT NOT NULL,
  `Matricula` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `avatar` LONGBLOB NOT NULL,
  `acesstype` BIT(1) NOT NULL,
  PRIMARY KEY (`idsys_user`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
